//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom04_CNPM_WebsiteGoiYDiaDiemDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompareSessionItem
    {
        public int Id { get; set; }
        public System.Guid SessionId { get; set; }
        public int PlaceId { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual CompareSession CompareSession { get; set; }
    }
}
