//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom04_CNPM_WebsiteGoiYDiaDiemDuLich.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelSuggestEntities : DbContext
    {
        public TravelSuggestEntities()
            : base("name=TravelSuggestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompareSessionItem> CompareSessionItems { get; set; }
        public virtual DbSet<CompareSession> CompareSessions { get; set; }
        public virtual DbSet<FavoritePlace> FavoritePlaces { get; set; }
        public virtual DbSet<PlaceImage> PlaceImages { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<PlaceTag> PlaceTags { get; set; }
        public virtual DbSet<PlaceType> PlaceTypes { get; set; }
        public virtual DbSet<PlanItem> PlanItems { get; set; }
        public virtual DbSet<PlanShare> PlanShares { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<SearchHistory> SearchHistories { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TravelPlan> TravelPlans { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<PasswordReset> PasswordResets { get; set; }
        public virtual DbSet<BlogPostPlace> BlogPostPlaces { get; set; }
        public virtual DbSet<BlogPost> BlogPosts { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
    }
}
