//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom04_CNPM_WebsiteGoiYDiaDiemDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceTag
    {
        public int PlaceTagId { get; set; }
        public int PlaceId { get; set; }
        public int TagId { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
