//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom04_CNPM_WebsiteGoiYDiaDiemDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanShare
    {
        public int ShareId { get; set; }
        public int PlanId { get; set; }
        public string ShareToken { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ExpiredAt { get; set; }
    
        public virtual TravelPlan TravelPlan { get; set; }
    }
}
