//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom04_CNPM_WebsiteGoiYDiaDiemDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHistory
    {
        public int SearchId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Keyword { get; set; }
        public string FiltersJson { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
