//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom04_CNPM_WebsiteGoiYDiaDiemDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelPlan()
        {
            this.PlanItems = new HashSet<PlanItem>();
            this.PlanShares = new HashSet<PlanShare>();
        }
    
        public int PlanId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> MoveCost { get; set; }
        public Nullable<decimal> StayCost { get; set; }
        public Nullable<decimal> FoodCost { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string Itinerary { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanItem> PlanItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanShare> PlanShares { get; set; }
        public virtual User User { get; set; }
    }
}
